spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.103/shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: C:\My_Project_file\workspaces\IdeaProjects\sell\varlog
#  level:
#    com.imooc.LoggerTest: debug
